### ISSUE TITLE
is networkx dependence crucial for polytope?

### ISSUE THREAD

**Issue by necozay** [tulip-control/polytope#12]
or is it just a reminiscence of tulip? partitions seem to use it. not sure if it can be replaced by sparse matrices or if there are future plans for using networkx more.

**Comment by johnyf** [comment]
Keeping `networkx` as a requirement does not add any complexity to the installation, and can be used more widely in the future. Refactoring of `tulip` abstraction algorithms to use `networkx` will be pursued in the issue linked to [above](https://github.com/tulip-control/polytope/issues/12#issuecomment-48131394).
