### ISSUE TITLE
Create MacPorts Portfile and contribute upstream

### ISSUE THREAD

**Issue by slivingston** [tulip-control/polytope#14]
Motivated by progress toward having a `tulip-control` port (cf. tulip-control/tulip-control#15), a Portfile should be created for `polytope` and contributed to the [MacPorts Project](http://www.macports.org/).  This will simplify installation for a broad audience using MacOS.  Since `polytope` already has an [entry on PyPI](https://pypi.python.org/pypi/polytope), I expect that creation and acceptance of this Portfile will be easily achieved.

**Comment by johnyf** [comment]
Following the conclusion of the corresponding [`tulip` #15](https://github.com/tulip-control/tulip-control/issues/15), GLPK is available in MacPorts. Offering `polytope` elsewhere than PyPI is nested (against PEP20) and is not related to linking `cvxopt.glpk`.

The recommended installation approach is to get non-Python dependencies with a suitable package manager (MacPorts, `apt`), then install Python, a `virtualenv`, and clone `cvxopt` to compile and link it to the GLPK headers installed by the package manager. This allows for frequent updates from the latest versions on PyPI, and is flat.
