### ISSUE TITLE
make plotting independent of `tulip`

### ISSUE THREAD

**Issue by johnyf** [tulip-control/polytope#27]
`polytope.polytope` and `polytope.plot`both depend on`tulip.graphics`for plotting (remnants from a time when`polytope`was a subpackage of`tulip`). For example:

https://github.com/tulip-control/polytope/blob/3a721bc36f178004c0003708648bf0988ab47fd6/polytope/polytope.py#L397
https://github.com/tulip-control/polytope/blob/4b3d1c3d28c344285557b4bbdff65aedb88a841a/polytope/plot.py#L81

`polytope` is a dependency of `tulip`. Therefore, it cannot itself depend on `tulip`, because this results in a cyclic dependency (hence the labeling as "bug").
The usage is very limited: `tulip.graphics.newax` and `tulip.graphics.dom2vec`, both of which are small or eliminable.

The module `tulip.graphics` originates from my porting to Python part of plotting utilities that I had developed in Matlab.  In Python, either some things are not needed at all, or there is a much better and simpler way to do them, or someone - like `matplotlib` and friends - has already written what is needed. Also, `tulip.graphics` derives from code that was handling seamless plotting in 2 or 3 dimensions, which in practice is not used in `tulip` or `polytope` (and I don't think it would be very practical to plot 3D partitions).

**Comment by johnyf** [comment]
A second flaw in the design (by me) is that `Polytope.plot` returns silently (!) if `tulip.graphics.newax` fails to import. It should raise `ImportError`, because requesting a plot and not getting one is an error, and "Errors should never pass silently. Unless explicitly silenced." (PEP 20).

**Comment by slivingston** [comment]
Thanks for creating this issue. I noticed the unnecessary dependence on `tulip` previously but had not taken action.

**Comment by johnyf** [comment]
Addressed as of 9d96bc0c65c3aeed94a655672cdb59c2f4491ebf. Plotting needs to be tested more, but that is a separate issue.
