### ISSUE TITLE
write tutorial in documentation

### ISSUE THREAD

**Issue by johnyf** [tulip-control/polytope#5]
Currently there is no documentation at all, which would have been useful also in `tulip`.

**Comment by johnyf** [comment]
I suggest that we use GitHub pages, which works from a Markdown file, without need for extra steps or dependencies. Branches other than `gh-pages` [are supported](https://help.github.com/articles/user-organization-and-project-pages/), but I think `gh-pages` is the simplest option with the least effect on branch `master`. To update the documentation, we can either push new commits, or replace the commit with the old version.

I have pushed the tutorial to `gh-pages`. The result is at: http://tulip-control.github.io/polytope/. If there is agreement, I think we can close this issue.

**Comment by slivingston** [comment]
* I think that this solution is good, and that the issue #5 can be closed. Perhaps wait at most 1 more day for admonitions.
* A link should be provided from the root README. I recommend to prefer the HTTPS URL: <https://tulip-control.github.io/polytope/>
* Manually renaming doc/tutorial.md to index.md is a hassle. If you agree, I shall make a script to automate this.
* For the sake of complete instructions about rebuilding stuff, I recommend that an explicit note is included about the documentation release being built with Jekyll via GitHub Pages (https://jekyllrb.com/docs/github-pages/).

**Comment by johnyf** [comment]
I agree with the documentation changes, which have been added on branch `doc`, and about creating a copying script.

**Comment by slivingston** [comment]
I reviewed your changes on the `doc` branch, and I added a shell script, `doc/build.sh`, that automates the release process except for `git push`. Some users might not find the script useful, but it also serves as documentation for how to manually perform the release.

**Comment by slivingston** [comment]
@johnyf  I commented on one of the commits: https://github.com/tulip-control/polytope/commit/462f817af1782d8a23e83e8aea7d3f2f6e663ebb#commitcomment-24813889

Deleting or keeping in the comments (as you have) does not seem critical because we plan to eventually audit or freshly write that function.

**Comment by johnyf** [comment]
Given that the line was unused in the past, I will change that commit to delete the line. I will merge the branch `doc` into `master` later today.

**Comment by johnyf** [comment]
Addressed by 77b6436946a7a4585222df7dcc351ead704f8e39 and b8a1e9ff243e7a057a48bd7d1cc97ae560fb33c2.
