### ISSUE TITLE
support Python 3.7

### ISSUE THREAD

**Issue by slivingston** [tulip-control/polytope#54]
The future is upon us. At the time of opening this issue, visiting <https://docs.python.org/> results in documentation for Python version 3.7. We should support it:

- [x] add to list of classifiers in setup.py
- [x] add to test matrix on Travis CI (.travis.yml) (EDIT: now done in GitHub Action .github/workflows/main.yml)
- [x] skim the "What's New?" section of the 3.7 announcement, and check for parts of Polytope that might be broken from it;
- [x] if any code changes for compatibility, write regression tests

**Comment by johnyf** [comment]
Added Python 3.7 and 3.8 to test environments in commit 6b855cda9b4cae066c79cc2a10a94e99c2a8df1c and the Trove classifiers for Python 3.7 and 3.8 in commit 215143c9b0712499d25b14cf9bb6c09d66fe4d47.

**Comment by slivingston** [comment]
Sufficiently operational with Python >= 3.8 to close this issue.
