### ISSUE TITLE
polytope volume changing on each trial

### ISSUE THREAD

**Issue by mvnayagam** [tulip-control/polytope#81]
Dear Developers & users,
recently I face an issue with polytope.  I use jupyter notebook for all calculations 
here is an example:
a=np.array([ [ 0.57735,-0.57735, -0.57735], [-0.57735,-0.57735,  0.57735], [ 0.57735, 0.57735, -0.57735], [ 0.     , 0.     ,  1.     ],
 [-0.57735, 0.57735,  0.57735], [-0.     ,-0.     , -1.     ]])
b = np.array([[-0.0241 , -0.19315 , 0.20914,  0.16667,  0.03683 ,-0.125  ]])

s=pc.Polytope(da,db)

print(" Volume is : ", s.volume)

executing the cell prints volume. "Volume is :  1.3701285938484307e-05"

again if I execute the cell then I get a different volume value. Executing for the second time print "Volume is : 1.2551849198678577e-05"

on third Execution: " Volume is :  1.3241511242562017e-05 "

every time the value is changing. what causes this issue in polytope pacakage ?

Though the values are small, I do not expect different volumes for the same polytope defined using the same "a & b".

Looking forward to your suggestions
 
thank you 

---
Best regards,
Muthu
TU Feriberg, Feriberg, Germany

**Comment by necozay** [comment]
Volume algorithm in the polytope package is a randomized (sampling based) algorithm that aims to approximate the volume. It is neither exact nor deterministic. More details here: https://github.com/tulip-control/polytope/issues/69#issuecomment-849696661
