### ISSUE TITLE
Updated release on PyPI?

### ISSUE THREAD

**Issue by victoraalves** [tulip-control/polytope#83]
Hi everyone,

Are there any plans for a new release soon? 

The most updated version of the codebase had some bugs that were fixed, when compared to 0.2.3, that would be nice to have on pip due to automatic dependency handling. I am building a [package](https://codes-group.github.io/opyrability/intro.html) that uses Polytope's algorithms and it would be nice to have the most up-to-date code available on pip. 

Thanks for making this nice package available to the community!

**Comment by slivingston** [comment]
Thanks for asking, and thanks for pointing us to your package! We will make a release as soon as possible, likely Monday, 28 August.

**Comment by victoraalves** [comment]
Thank you! Polyope has been incredibly helpful to us!

**Comment by victoraalves** [comment]
That's awesome. Thanks a lot!
