### ISSUE TITLE
MIB2 cannot clear 01637 error

### ISSUE THREAD

**Issue by mihaymihay** [tulip-control/polytope#86]
hy after i installed mib2 tool box i cannot clear the 01637 error usb comunication

**Comment by slivingston** [comment]
@mihaymihay can you give more details? Should this issue be on a different project? There is not any USB-related code here.

**Comment by mihaymihay** [comment]
This error my usb won’t communicate with the media Sent from my iPhoneOn 28 Nov 2023, at 01:47, Scott C. Livingston ***@***.***> wrote:﻿
@mihaymihay can you give more details? Should this issue be on a different project? There is not any USB-related code here.

**Comment by slivingston** [comment]
I am going to assume you are asking on the wrong issues tracker. You can re-open if you have more details.
